plugins {
    id 'java'
    id 'application'
    id 'idea'
}

group 'org.example'
version '1.0.0'

sourceCompatibility = 21

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.tika:tika-core:2.9.2'
    implementation 'org.jetbrains:annotations:24.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
}

application {
    mainClass = 'hanziToAnki.Main'
}

sourceSets {
    main {
        java {
            exclude 'GUIs/**'
            exclude 'server/**'
            exclude 'utils/**'
        }
    }
    test {
        java {
            exclude '**/GeneratorControllerTest.java'
        }
    }
}

compileJava {
    options.encoding = "UTF-8"
    options.release = 21
}

compileTestJava {
    options.encoding = "UTF-8"
    options.release = 21
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

jar {
    manifest {
        attributes('Main-Class': 'hanziToAnki.Main')
    }
    archiveFileName = "HanziToAnki.jar"
}
